package appcore

import (
	"encoding/json"
	"errors"
)

const clientSearchWire = "momo__client_tool_search"

var errUnsupportedToolLoading = errors.New("unsupported_tool_loading")
var errUnsupportedSearchSchema = errors.New("unsupported_search_schema")

// Explicit compatibility policy, not native deferred prompt/cache layout. Only
// already-loaded definitions are disclosed in the current provider tool list.
// Lifecycle validation processes the original input in order before projection.
type toolLoading struct {
	active      map[string]bool
	definitions map[string]string
	constraints map[string]map[string]any
	topDeferred map[string]bool
	search      map[string]any
	seen        map[string]bool
	pending     string
}

func newToolLoading(p map[string]any) (*toolLoading, error) {
	policy, present := p["momo_tool_loading"]
	if !present {
		return nil, nil
	}
	if policy != "client-search" || p["parallel_tool_calls"] != false {
		return nil, errUnsupportedToolLoading
	}
	return &toolLoading{active: map[string]bool{}, definitions: map[string]string{}, constraints: map[string]map[string]any{}, topDeferred: map[string]bool{}}, nil
}

func (l *toolLoading) declare(t map[string]any, ns, wire, source string) (bool, error) {
	deferred := false
	if v, present := t["defer_loading"]; present {
		b, ok := v.(bool)
		if !ok {
			return false, errRouted
		}
		deferred = b
	}
	if source == "top" {
		if old, present := l.topDeferred[wire]; present && old != deferred {
			return false, errRouted
		}
		l.topDeferred[wire] = deferred
	}
	core := map[string]any{}
	for k, v := range t {
		if k != "defer_loading" {
			core[k] = v
		}
	}
	core["namespace"] = ns
	b, err := json.Marshal(core)
	if err != nil {
		return false, errRouted
	}
	if old, ok := l.definitions[wire]; ok {
		if old != string(b) {
			return false, errRouted
		}
		if source == "loaded" {
			l.active[wire] = true
		}
		return true, nil
	}
	l.definitions[wire] = string(b)
	l.active[wire] = source == "loaded" || !deferred
	return false, nil
}

func (l *toolLoading) input(m map[string]any, messages *[]routeMessage, seen map[string]bool, load func([]any) error) error {
	switch m["type"] {
	case "additional_tools":
		if l.pending != "" || !only(m, "type", "role", "tools") || m["role"] != "developer" {
			return errRouted
		}
		defs, ok := m["tools"].([]any)
		if !ok || len(defs) == 0 {
			return errRouted
		}
		// This compatibility mode accepts additional_tools as explicit loaded
		// declarations. A deferred additional declaration is ambiguous here;
		// require discovery through a paired search result instead of guessing.
		for _, def := range defs {
			if hasDeferredDefinition(obj(def)) {
				return errUnsupportedToolLoading
			}
		}
		return load(defs)
	case "tool_search_call":
		if l.pending != "" || l.search == nil || !only(m, "type", "execution", "call_id", "arguments") || m["execution"] != "client" {
			return errRouted
		}
		id, ok := m["call_id"].(string)
		if !ok || id == "" || len(id) > 64 || seen[id] || len(seen) >= 128 {
			return errRouted
		}
		args := obj(m["arguments"])
		if args == nil || validateSearchValue(l.search, args) != nil {
			return errRouted
		}
		b, err := json.Marshal(args)
		if err != nil {
			return errRouted
		}
		call := routeCall{id: id, wire: clientSearchWire, args: string(b)}
		if len(*messages) == 0 || (*messages)[len(*messages)-1].role != "assistant" {
			*messages = append(*messages, routeMessage{role: "assistant"})
		}
		last := &(*messages)[len(*messages)-1]
		last.calls = append(last.calls, call)
		last.parts = append(last.parts, routePart{call: &call})
		seen[id] = true
		l.pending = id
		return nil
	case "tool_search_output":
		if l.pending == "" || m["call_id"] != l.pending || m["execution"] != "client" || !only(m, "type", "execution", "call_id", "tools") {
			return errRouted
		}
		defs, ok := m["tools"].([]any)
		if !ok {
			return errRouted
		}
		if err := load(defs); err != nil {
			return err
		}
		// Search results are data returned by the client, not developer prose or
		// instructions generated by this proxy. Never run a search/MCP process.
		b, err := json.Marshal(map[string]any{"tools": defs})
		if err != nil {
			return errRouted
		}
		*messages = append(*messages, routeMessage{role: "tool", resultID: l.pending, text: string(b)})
		l.pending = ""
		return nil
	}
	return errRouted
}

func hasDeferredDefinition(t map[string]any) bool {
	if t["defer_loading"] == true {
		return true
	}
	if t["type"] == "namespace" {
		children, _ := t["tools"].([]any)
		for _, child := range children {
			if hasDeferredDefinition(obj(child)) {
				return true
			}
		}
	}
	return false
}
