// Package integration contains secret-free, explicit client exports.
package integration

import (
	_ "embed"
	"encoding/json"
)

//go:embed SKILL.md
var Skill string

func MCPConfig(executable string) string {
	data, _ := json.MarshalIndent(map[string]any{"mcpServers": map[string]any{"momo-preview": map[string]any{"command": executable, "args": []string{"mcp"}}}}, "", "  ")
	return string(data)
}

func Capabilities() map[string]any {
	files := map[string]any{"input_files": "ordered bounded PDF only; canonical inline file_data, Claude/Gemini delegated HTTPS file_url with explicit application/pdf; Chat inline only; max16 PDFs/32 images share decoded 1MiB and JSON/history limits; header/EOF framing not structure/safety; no reads/cloud uploads/fetch; explicit local memory snapshots separately described", "tool_files": "paired PDF: Claude nested; Chat/ALL Gemini explicit momo_tool_files:user-projection, mixed images require momo_tool_images too; non-native trust equivalence; re-declare for history/compact; no automatic fallback", "max_pdfs": 16}
	capabilities := map[string]any{"routes": []string{"GET /v1/models", "POST /v1/responses", "POST /v1/chat/completions", "POST /v1/responses/compact"}, "protocol": "default exact passthrough; opt-in partial MOMO Responses/Chat/Claude/Gemini routing with SSE or final JSON", "compact": "explicit X-MOMO-Compact:native request for native Responses model forwards exact JSON; capability/live semantics unverified, no fallback; otherwise explicit routing-mode local lossy checkpoint with ordinary output replay, no opaque or anchor state", "tool_loading": "explicit momo_tool_loading:client-search + parallel_tool_calls:false; ordered client-loaded definitions/local bounded strict validation, not native prompt/cache or constrained generation; no proxy execution", "output_limits": "converted max_output_tokens integer 1..1048576; verified limit terminal is incomplete, never a history anchor", "history": "converted memory anchors default same-model; explicit request X-MOMO-History:replay-v1 permits canonical transcript re-encoding across converted Chat/Claude/unsigned Gemini models, not native opaque/signed/provider/account equivalence; target tools/options re-declared, exact full-prefix dedup, source immutable and LRU success-only; Stop/configure clears, no transcript export", "mcp": "read-only stdio capability tool and skill resource", "input_images": "converted ordered user inline PNG/JPEG/static GIF/WebP or delegated HTTPS references; same-model history; header/framing only, no fetch/DNS/redirect validation; Gemini URL requires explicit mime_type; no cloud uploads or generation; explicit local memory snapshots separately described", "tool_images": "paired outputs: Claude nested; unsigned Gemini3 inline native parts with MOMO ordered index JSON; Chat/legacy Gemini need explicit momo_tool_images:user-projection, non-native role/trust equivalence; no auto fallback/execution", "media": false, "model_routing": "opt-in partial", "cross_device": false, "account_wallet": false}
	for key, value := range files {
		capabilities[key] = value
	}
	capabilities["tool_text"] = "request-scoped X-MOMO-Tool-Text:dsml-v1 on converted Chat Responses only; never default/forwarded/inherited. Bounded strict plain/ASCII/fullwidth DSML invoke/parameter conversion, exact raw strings or explicit string=false JSON, declared tool identity/namespace/choice gates. No marker-prefix leak, mixed structured/text tools or truncated/length/search completion. Typed parameter difference from Node's string/trim parser, no XML entity decoding in values or tool execution/live-model guarantee. 128 calls/parameters,1MiB retained; only verified finish+[DONE] completes and commits history."
	capabilities["diagnostics"] = "explicit native Settings current-Core allowlisted runtime/status/limits/retained-live aggregate snapshot; no endpoint/port/key/model/item/task IDs/content/account paths, no network/vault/client lookup or expiry/LRU mutation. Native Origin+page capability only, no public API/MCP tool. CLI diagnostics describes fresh offline-process only, not running desktop health; no stdin/env/config/Core/listener/GUI. No upload/copy/save or automatic reads; not provider/inference/account verification."
	capabilities["image_generation"] = "authenticated non-browser GET /internal/images/capabilities then explicit POST /internal/images/generate; known catalog-authorized generation profiles only; 5min permission, 300s bounded send, no retries/model substitution. GET /internal/images/tasks/<id> only generation-returned IDs in this Core:64 slots/absolute30minTTL, Stop/configure clears. Bounded JSON URL/Base64/tasks; public HTTPS URLs delegated without download/DNS checks, inline framing not pixel safety. Desktop workbench explicit catalog/model/consent generation/manual latest-task and opt-in data-only preview; URL text not auto-loaded; Stop/configure/load clear UI and fence late results. No edit/video/disk assets; media:false means full media suite unimplemented. Upstream calls may bill; failed delivery/Stop cannot undo them."
	capabilities["image_mcp"] = "separate opt-in mcp-images owns Core with private stdin config prelude; mcp-images-connect --endpoint exact http://127.0.0.1:<port> attaches to running gateway using explicitly set MOMO_LOCAL_API_KEY local session env only (no upstream/account discovery). Desktop separately copies credential-free generic mcpServers config; normal mcp export remains read-only. image_capabilities/image_generate/image_task: client confirmed:true is NOT verified human consent; catalog first, one send, no retry/poll/download/redirect/proxy. Text JSON only, no image blocks/disk/edit/video; current gateway returned session IDs/TTL only. No auto query at initialize/list; connector EOF/signal does not stop gateway, Stop/configure invalidates media session, relaunch changes port/token. Sequential EOF between calls, pending disconnect bounded by deadlines; local signal cancels IO/call, not remote jobs. Official MCP SDK interoperability tested with synthetic local gateway, not actual agent/live model proof."
	capabilities["client_config"] = "explicit desktop clipboard export of credential-free user-level Codex provider snippet; loopback port + MOMO_LOCAL_API_KEY env reference; no model/client file/account access, no installation; actual agent compatibility unverified"
	capabilities["client_policy"] = "optional per-request X-MOMO-Client-Policy:text-tools-v1 on converted POST /v1/responses only; explicit lossy no-summary/encrypted-continuation/cache contract, not inherited; native/default exact bytes. Private client labels/cache/include validated and omitted; namespace descriptions kept, strict:false existing shim and preserved parallel booleans with explicit per-turn output count gate; valid tool-output IDs normalize labels only, call_id/schema/pairing/content remain strict. Grammar/search/strict:true/signatures/unknown options still gated. Secret-free CLI codex-text-tools-catalog --model gpt-5.5 emits one manually reviewed conservative CLIENT catalog, not actual model availability/context/inference proof; no client file writes or auto selection. Actual Codex0.156 generic synthetic read-only exec/output/second turn tested; not full agent/live parity."
	capabilities["video_generation"] = "explicit authenticated non-browser GET /internal/videos/capabilities queries token-scoped /v1/models only: MiniMax-H3-Max/seedance-2.5 APIMart JSON subset. Static controls from documented Node adapter, NOT advanced-control/live-inference proof; no preference/substitution. POST /internal/videos/generate needs fresh5min catalog/explicit model; text or delegated HTTPS references/frames, no local upload/asset IDs/audio/video refs/legacy Adobe route. One 60s send, no retry; shared4admission/1MiB request/16MiB response. GET /internal/videos/tasks/<id> only IDs this Core returned:64reservedslots/absolute30minTTL, Stop/configure clears, not remote cancel. Bounded known task JSON, normalized status/redacted errors/HTTPS URL text, no download/playback/authenticated content URL. Desktop video workbench: explicit catalog/model/duration/resolution/ratio/consent, optional public HTTPS reference/frame JSON, manual latest task, URL text only; no playback/download. Origin+page capability/shared native mutation gate, Stop/configure/load clear and fence late responses. Separate opt-in video MCP described below; media:false means full suite unfinished."
	capabilities["video_mcp"] = "separate opt-in mcp-videos owns Core with private stdin config line; mcp-videos-connect --endpoint exact current IPv4 loopback uses explicit MOMO_LOCAL_API_KEY local full-session token, NOT upstream key/media-only scope. No vault/account/Node discovery/client file edits. Desktop copies credential-free config only while Running and with Origin+page capability. Default readonly and image tools remain isolated. video_capabilities/video_generate/video_task reuse Core APIMart constraints/catalog5min/task64slots+absolute30minTTL/Stop clear/shared4admission. confirmed:true is NOT verified human consent; trusted client obtains intent, generation may bill. No init/list queries, one send/no retry/poll/download/play/content URL. Connected20s catalog/65s generation/task;160KiB duplicate-free depth64 lines/16MiB text JSON only/fixed errors/shortwrite abort. Sequential EOF between calls, pending disconnect bounded by deadlines; signal cancels local IO/work, not remote billing. Connector EOF/signal never stops gateway. Not existing Node plugin/fullmedia/actualagent/liveinference proof."
	capabilities["attachments"] = "routing-mode only: POST /internal/attachments registers one validated inline image/PDF part, GET/DELETE /internal/attachments/att_<random64hex> metadata/deletion; no listing/content export; per-Core 64 entries/8MiB canonical JSON/absolute30minTTL, Stop/configure clears. X-MOMO-Attachments:inline resolves exact user.content or paired tool.output momo_attachment refs only on converted Responses/localcompact. Full inline history snapshots survive asset deletion/expiry; deleted full refs reject. Not cloud upload, provider file_id, disk storage, cross-device or media generation; no account/key access through MCP"
	capabilities["tool_aliases"] = "converted Chat/Claude/Gemini only: original namespace/name each ASCII [A-Za-z0-9_-] 1..64 bytes; long flattened and reserved synthetic spellings use deterministic 64-byte mta_ full structured-identity SHA-256 aliases. Shared declarations/selectors/history/client-loading/DSML mapping; canonical output restores originals. Short nonreserved unchanged, functions top-level; unknown reserved wires/ambiguous bare names/flatten collisions reject. No truncation/guessing/Unicode or overlong component/native-byte/provider acceptance guarantee."
	capabilities["parallel_tools"] = "converted explicit parallel_tool_calls bool: false at most one NEW function/custom/DSML/search call, true multiple, absent default unchanged. Chat forwards bool; Claude auto/any/tool inverse disable_parallel_tool_use (none no extra field); Gemini local count gate only, no invented wire field. Two calls fail without completed/incomplete/history, JSON502 or SSE abort (first proposal may already be exposed), no retry/execution/billing rollback or provider constrained-generation guarantee. Historical parallel calls valid, constraint not inherited; text-tools-v1 preserves booleans. Invalid/duplicate flags reject before send; native/default bytes unchanged; client-search remains false-only."
	return capabilities
}
