// Package integration contains secret-free, explicit client exports.
package integration

import (
	_ "embed"
	"encoding/json"
)

//go:embed SKILL.md
var Skill string

func MCPConfig(executable string) string {
	data, _ := json.MarshalIndent(map[string]any{"mcpServers": map[string]any{"momo-preview": map[string]any{"command": executable, "args": []string{"mcp"}}}}, "", "  ")
	return string(data)
}

func Capabilities() map[string]any {
	files := map[string]any{"input_files": "ordered bounded PDF plus inline UTF8 text/plain,text/markdown,text/csv for Claude/Gemini; canonical Base64, UTF8 and non-control text validation (tab/CR/LF allowed), original bytes retained; native plaintext document/inlineData MIME text/plain, not rendering/injection safety. Chat non-PDF rejects, no silent projection. PDF delegated HTTPS file_url only explicit application/pdf with Claude/Gemini; Chat PDF inline only; max16 TOTAL files/32 images share decoded 1MiB and JSON/history/wire limits; PDF header/EOF framing not structure/safety; no reads/cloud uploads/fetch; local memory snapshots separately described", "tool_files": "paired PDF/text: Claude nested native documents; Chat PDF/ALL Gemini explicit momo_tool_files:user-projection, mixed images require momo_tool_images too; non-native trust equivalence; re-declare for history/compact; no automatic fallback", "max_pdfs": 16, "max_files": 16, "text_file_mimes": []string{"text/plain", "text/markdown", "text/csv"}}
	capabilities := map[string]any{"routes": []string{"GET /v1/models", "GET /models", "POST /v1/responses", "POST /responses", "POST /v1/chat/completions", "POST /chat/completions", "POST /v1/responses/compact", "POST /responses/compact"}, "protocol": "default exact passthrough; opt-in partial MOMO Responses/Chat/Claude/Gemini routing with SSE or final JSON", "compact": "explicit X-MOMO-Compact:native request for native Responses model forwards exact JSON; capability/live semantics unverified, no fallback; otherwise explicit routing-mode local lossy checkpoint with ordinary output replay, no opaque or anchor state", "tool_loading": "explicit momo_tool_loading:client-search + parallel_tool_calls:false; ordered client-loaded definitions/local bounded strict validation, not native prompt/cache or constrained generation; no proxy execution", "output_limits": "converted max_output_tokens integer 1..1048576; verified limit terminal is incomplete, never a history anchor", "history": "converted memory anchors default same-model; explicit request X-MOMO-History:replay-v1 permits canonical transcript re-encoding across converted Chat/Claude/unsigned Gemini models, not native opaque/signed/provider/account equivalence; target tools/options re-declared, exact full-prefix dedup, source immutable and LRU success-only; Stop/configure clears, no transcript export", "mcp": "read-only stdio capability tool and skill resource", "input_images": "converted ordered user inline PNG/JPEG/static GIF/WebP or delegated HTTPS references; same-model history; header/framing only, no fetch/DNS/redirect validation; Gemini URL requires explicit mime_type; no cloud uploads or generation; explicit local memory snapshots separately described", "tool_images": "paired outputs: Claude nested; unsigned Gemini3 inline native parts with MOMO ordered index JSON; Chat/legacy Gemini need explicit momo_tool_images:user-projection, non-native role/trust equivalence; no auto fallback/execution", "media": false, "model_routing": "opt-in partial", "cross_device": false, "account_wallet": false}
	for key, value := range files {
		capabilities[key] = value
	}
	capabilities["gemini_thinking"] = "explicit per-request generateContent momo_gemini_thinking: nonempty object, includeThoughts boolean preserves false, thinkingLevel MINIMAL/LOW/MEDIUM/HIGH OR thinkingBudget integer -1..2147483647 preserves0/-1 (disabled/automatic, model-dependent support). Effort minimal/low/medium/high maps exact levels; aliases agree, consistent explicit level allowed; budget+effort/xhigh/max/ultra/none reject. Unknown/null/combined level+budget reject. No model capability/range guesses, clamps/fallback/retry/history inheritance; generationConfig combines maxOutputTokens. Native/default byte passthrough unchanged; not Interactions API or signed streaming reconstruction/live-provider proof."
	capabilities["search_checkpoint"] = "explicit local client-search checkpoint retains whole completed search/loading/call-result turns including additional_tools and media interpretation; same bounded IR revalidates framing/identity/schema/order. Re-declare tools, client-search/parallel false and applicable media policies for ordinary output replay; no upstream, hidden anchor, automatic client integration or semantic summary. Pending/unsafe/no-benefit rejected."
	capabilities["gemini_state"] = "bounded generateContent Part subset: public thought:true text -> separate reasoning summary, provider-issued text/function/custom thoughtSignature -> momo_gemini:{model,thought_signature}. Exact same-model full/suffix replay preserves state/part order/empty signed text; different-model replay rejects even explicit replay-v1. Checkpoint protects entire state-bearing turns. Canonical Base64 <=256KiB/signature, 2048 native Parts, 1MiB retained/history/wire budgets; duplicate-free UTF8 depth64 frames; no completion/history on malformed/incomplete/cancelled/failed delivery. No cryptographic verification, signature fabrication/bypass, signature-only/partialArgs/output-media Parts, Interactions API or full signed streaming compatibility/live-provider guarantee."
	capabilities["claude_state"] = "bounded Messages thinking/redacted_thinking blocks: provider public summary -> separate reasoning summary; opaque signature/data -> momo_claude:{model,type,signature|data}, NOT Base64 validation/decryption/crypto verification. Exact same-model ordered full/suffix replay, empty thinking retained, redacted summary empty; different-model rejects even replay-v1, checkpoint protects whole state-bearing turn. Explicit momo_claude_thinking adaptive/enabled/disabled native controls; display summarized/omitted, manual budget>=1024 and <max_tokens; effort low/medium/high/xhigh/max requires explicit adaptive control, sent as output_config.effort, no guessed model support/budget/clamp/-thinking alias. Thinking rejects forced tool choice. Single final signature_delta, strict UTF8/duplicate-free/depth64 and unpaired-surrogate rejection,128 blocks/256KiB opaque/1MiB retained-history-wire. Verified final thinking_tokens maps reasoning_tokens; no fabricated usage. Completion/history requires clean EOF and successful terminal write; failures/incomplete/cancel/Stop/store:false do not mint anchors. No updates/interleaved beta/output media/full native stream or live-provider guarantee."
	capabilities["tool_text"] = "request-scoped X-MOMO-Tool-Text:dsml-v1 on converted Chat Responses only; never default/forwarded/inherited. Bounded strict plain/ASCII/fullwidth DSML invoke/parameter conversion, exact raw strings or explicit string=false JSON, declared tool identity/namespace/choice gates. No marker-prefix leak, mixed structured/text tools or truncated/length/search completion. Typed parameter difference from Node's string/trim parser, no XML entity decoding in values or tool execution/live-model guarantee. 128 calls/parameters,1MiB retained; only verified finish+[DONE] completes and commits history."
	capabilities["diagnostics"] = "explicit native Settings current-Core allowlisted runtime/status/limits/retained-live aggregate snapshot; no endpoint/port/key/model/item/task IDs/content/account paths, no network/vault/client lookup or expiry/LRU mutation. Native Origin+page capability only, no public API/MCP tool. CLI diagnostics describes fresh offline-process only, not running desktop health; no stdin/env/config/Core/listener/GUI. No upload/copy/save or automatic reads; not provider/inference/account verification."
	capabilities["function_strict"] = "ordinary converted function strict:true independent of client-search/single-call; root object, bounded unique known type unions including nullable nested objects/arrays, exact numeric/Unicode limits, depth16/nodes2048/enum128; all strict objects require all properties and additionalProperties:false. Explicit Chat function.strict bool retained; no invented Claude/Gemini strict field. false/absent no local schema constraint. Historical/generated args and pre-reserialization duplicate/UTF8/depth64 framing validated; abort/502 without completion/history/retry, no client-execution/billing rollback or provider constrained-generation/grammar/full JSON Schema guarantee."
	capabilities["image_generation"] = "authenticated non-browser GET /internal/images/capabilities then explicit POST /internal/images/generate; known catalog-authorized generation profiles only; 5min permission, 300s bounded send, no retries/model substitution. GET /internal/images/tasks/<id> only generation-returned IDs in this Core:64 slots/absolute30minTTL, Stop/configure clears. Bounded JSON URL/Base64/tasks; public HTTPS URLs delegated without download/DNS checks, inline framing not pixel safety. Desktop workbench explicit catalog/model/consent generation/manual latest-task and opt-in data-only preview; URL text not auto-loaded; Stop/configure/load clear UI and fence late results. Separate catalog-authorized JSON reference editing is exposed as image_editing; no mask/legacy GPT Chat-media edit/video/disk assets; media:false means full media suite unimplemented. Upstream calls may bill; failed delivery/Stop cannot undo them."
	capabilities["image_mcp"] = "separate opt-in mcp-images owns Core with private stdin config prelude; mcp-images-connect --endpoint exact http://127.0.0.1:<port> attaches to running gateway using explicitly set MOMO_LOCAL_API_KEY local session env only (no upstream/account discovery). Desktop separately copies credential-free generic mcpServers config; normal mcp export remains read-only. image_capabilities/image_generate/image_edit/image_task: client confirmed:true is NOT verified human consent; catalog first, one send, no retry/poll/download/redirect/proxy. Text JSON only, no image blocks/disk/mask/legacy GPT Chat-media-edit/video; current gateway returned session IDs/TTL only. No auto query at initialize/list; connector EOF/signal does not stop gateway, Stop/configure invalidates media session, relaunch changes port/token. Sequential EOF between calls, pending disconnect bounded by deadlines; local signal cancels IO/call, not remote jobs. Official MCP SDK interoperability tested with synthetic local gateway, not actual agent/live model proof."
	capabilities["client_config"] = "explicit desktop clipboard export of credential-free user-level Codex provider snippet; loopback port + MOMO_LOCAL_API_KEY env reference; no model/client file/account access, no installation; actual agent compatibility unverified"
	capabilities["client_policy"] = "optional per-request X-MOMO-Client-Policy:text-tools-v1 on converted POST /v1/responses only; explicit lossy no-summary/encrypted-continuation/cache contract, not inherited; native/default exact bytes. Private client labels/cache/include validated and omitted; namespace descriptions kept, strict bool preserved (true bounded local validation, false non-strict shim) and preserved parallel booleans with explicit per-turn output count gate; valid tool-output IDs normalize labels only, call_id/schema/pairing/content remain strict. Grammar/search/unsupported strict schema/signatures/unknown options still gated. Secret-free CLI codex-text-tools-catalog --model gpt-5.5 emits one manually reviewed conservative CLIENT catalog, not actual model availability/context/inference proof; no client file writes or auto selection. Actual Codex0.156 generic synthetic read-only exec/output/second turn tested; not full agent/live parity."
	capabilities["video_generation"] = "explicit authenticated non-browser GET /internal/videos/capabilities queries token-scoped /v1/models only: MiniMax-H3-Max/seedance-2.5 APIMart JSON subset. Static controls from documented Node adapter, NOT advanced-control/live-inference proof; no preference/substitution. POST /internal/videos/generate needs fresh5min catalog/explicit model; text or delegated HTTPS references/frames, no local upload/asset IDs/audio/video refs/legacy Adobe route. One 60s send, no retry; shared4admission/1MiB request/16MiB response. GET /internal/videos/tasks/<id> only IDs this Core returned:64reservedslots/absolute30minTTL, Stop/configure clears, not remote cancel. Bounded known task JSON, normalized status/redacted errors/HTTPS URL text, no download/playback/authenticated content URL. Desktop video workbench: explicit catalog/model/duration/resolution/ratio/consent, optional public HTTPS reference/frame JSON, manual latest task, URL text only; no playback/download. Origin+page capability/shared native mutation gate, Stop/configure/load clear and fence late responses. Separate opt-in video MCP described below; media:false means full suite unfinished."
	capabilities["video_mcp"] = "separate opt-in mcp-videos owns Core with private stdin config line; mcp-videos-connect --endpoint exact current IPv4 loopback uses explicit MOMO_LOCAL_API_KEY local full-session token, NOT upstream key/media-only scope. No vault/account/Node discovery/client file edits. Desktop copies credential-free config only while Running and with Origin+page capability. Default readonly and image tools remain isolated. video_capabilities/video_generate/video_task reuse Core APIMart constraints/catalog5min/task64slots+absolute30minTTL/Stop clear/shared4admission. confirmed:true is NOT verified human consent; trusted client obtains intent, generation may bill. No init/list queries, one send/no retry/poll/download/play/content URL. Connected20s catalog/65s generation/task;160KiB duplicate-free depth64 lines/16MiB text JSON only/fixed errors/shortwrite abort. Sequential EOF between calls, pending disconnect bounded by deadlines; signal cancels local IO/work, not remote billing. Connector EOF/signal never stops gateway. Not existing Node plugin/fullmedia/actualagent/liveinference proof."
	capabilities["attachments"] = "routing-mode only: POST /internal/attachments registers one validated inline image/PDF/UTF8 text file part; registration is not provider support (Chat non-PDF rejects), GET/DELETE /internal/attachments/att_<random64hex> metadata/deletion; no listing/content export; per-Core 64 entries/8MiB canonical JSON/absolute30minTTL, Stop/configure clears. X-MOMO-Attachments:inline resolves exact user.content or paired tool.output momo_attachment refs only on converted Responses/localcompact. Full inline history snapshots survive asset deletion/expiry; deleted full refs reject. Not cloud upload, provider file_id, disk storage, cross-device or media generation; no account/key access through MCP"
	capabilities["tool_aliases"] = "converted Chat/Claude/Gemini only: original namespace/name each ASCII [A-Za-z0-9_-] 1..64 bytes; long flattened and reserved synthetic spellings use deterministic 64-byte mta_ full structured-identity SHA-256 aliases. Shared declarations/selectors/history/client-loading/DSML mapping; canonical output restores originals. Short nonreserved unchanged, functions top-level; unknown reserved wires/ambiguous bare names/flatten collisions reject. No truncation/guessing/Unicode or overlong component/native-byte/provider acceptance guarantee."
	capabilities["parallel_tools"] = "converted explicit parallel_tool_calls bool: false at most one NEW function/custom/DSML/search call, true multiple, absent default unchanged. Chat forwards bool; Claude auto/any/tool inverse disable_parallel_tool_use (none no extra field); Gemini local count gate only, no invented wire field. Two calls fail without completed/incomplete/history, JSON502 or SSE abort (first proposal may already be exposed), no retry/execution/billing rollback or provider constrained-generation guarantee. Historical parallel calls valid, constraint not inherited; text-tools-v1 preserves booleans. Invalid/duplicate flags reject before send; native/default bytes unchanged; client-search remains false-only."
	capabilities["desktop_image_save"] = "explicit inline result confirmation plus native SaveFile dialog, matching extension/new file only/O_EXCL;16MiB strict native envelope and validated original PNG/JPEG/static GIF/WebP bytes, no page paths/remote URL fetch/public API/MCP writer. Header validation not full integrity/safety. No automatic download/overwrite/retry; cancel no file, write/delivery failure may leave partial/complete file; Stop late UI fence not disk rollback. Windows UNC/device/ADS/reserved destinations denied; local filesystem/parent links not a sandbox."
	capabilities["image_editing"] = "authenticated POST /internal/images/edit after fresh catalog operations edit; fixed Web /v1/images/edits images, Adobe/legacy GPT /v1/images/generations image_urls, APIMart same path image_urls. Gemini3.1-flash-image fixed Chat messages prompt+one inline reference/modalities text-image/google.image_config; JSON finished choice0 assistant stop typed images/content image_url only, no SSE/prose scan/refusal/truncation/tools/duplicates/native candidates/task inference. Catalog count intersection with proxy safety ceiling Web/Adobe4, APIMart16, GPT/Gemini1; explicit mismatching transports deny edit, never reinterpret endpoints. Ordered validated inline PNG/JPEG/static GIF/WebP data URLs, APIMart optional lexically public HTTPS references delegated upstream (no DNS/content proof). Same bounded controls/300s/shared admission/task session/Stop as generation; duplicate/UTF8/depth64 strict. No masks/legacy GPT Chat media edits/uploads/file/asset IDs/fetch/fallback/downloads. Desktop operation+explicit local picker/reference text+fresh consent and opt-in image_edit MCP confirmed:true (not human proof);desktop edit1MiB envelope/Core1MiB wire, MCP160KiB lines. Token model-list fallback never authorizes editing. Mock evidence only, not live model/account parity."
	capabilities["plugin_media_calls"] = "Explicit mcp image|video --endpoint current IPv4 loopback plus intentionally inherited MOMO_LOCAL_API_KEY accepts Node-style flat generate/edit arguments and image_task_status/video_task_status. plugin-mcp-config prints secret-free launcher override only, no install/profile discovery. Client invocation expresses intent, NOT verified human consent; require user intent and explicit model/fresh catalog. Init/list no network; normal readonly/confirmed-request modes unchanged. Node-style model limits/parameter_schema reflect existing Core constraints, not live inference. URL/base64 JSON only; no image asset library/get/list/asset reuse/signed vision/automatic downloads. No video generate_audio/legacy routes. Not full unchanged installed-plugin/Skill parity; existing image Skill expects disk assets. One send, no retry/poll; errors fixed, same bounds/Stop/task-session semantics."
	capabilities["plugin_image_assets"] = "Explicit image launcher --asset-dir absolute NEW directory only; parent exists, no default/library discovery/import/overwrite. Inline PNG/JPEG/WebP results saved compactly, opaque asset:img_<sha256> edit reuse and image_asset_get/list with regular-file identity/hash/MIME validation. Connector-session IDs only; files survive exit but IDs cannot reopen. Absolute24h TTL/128entries/64MiB (failed writes charged), capacity reject no auto deletion, dedupe. Input160KiB, resolved edit/Core wire1MiB. URLs not downloaded, no signed vision/GIF/shared Node library/cross-device sync. Local metadata survives gateway Stop; generation/edit still Core catalog/model/Stop gated, one send/no retry; disk failure cannot undo billing. No implicit enable in exported launcher or default media modes. OS-owned mount/mapped drives not certified offline; not sandbox against same-account processes."
	capabilities["plugin_image_library"] = "Separate explicit --asset-library absolute path: create NEW marked Go library or reopen same format only, no home/account/Node/session import or directory scan. Fixed bounded marker/reserve+commit journal; reservation Sync before image creation, commit after image Sync+Close. OS nonblocking single-writer lifetime lock, process exit releases; no stale-lock deletion. Committed IDs/creation times/capacity reservations survive restart,24h absoluteTTL unchanged; uncommitted writes charged/invisible. Corrupt/torn records fail closed, no repair/truncation/deletion; requested images digest/MIME/regular identity verified. No encryption/shared Node library/remote URL download/signed vision/GIF/cloud sync/cross-device/power-loss guarantee. Existing --asset-dir session/default modes unchanged; no implicit export enable, network or generation at init/list. One connector per library; explicit local metadata scope, not complete plugin parity."
	return capabilities
}
