//go:build appcheck && !nogui

package main

// Executes the shipped page's DOM event handlers, not alternate fetch actions.
// Synthetic native test only, never compiled into the distributed application.
const pageProbeScript = `
async function check(){
 const started=await fetch('/check-page-ready',{method:'POST',headers:{'X-MOMO-Bridge':bridgeNonce}});if(!started.ok)throw Error('probe readiness denied');
 let step='initial';
 window.momoProbeStep=()=>step;const ensure=value=>{if(!value)throw Error('page check failed')};
 const request=async name=>{step=name;const r=await fetch('/'+name,{method:'POST',headers:{'X-MOMO-Bridge':bridgeNonce}});ensure(r.ok)};
 const button=async name=>{step=name;ensure(!byId(name).disabled);await byId(name).onclick()};
 const start=async phase=>{step=phase+'-start-enabled';ensure(!byId('start').disabled);step=phase+'-start-action';ensure(await byId('start').onclick());step=phase+'-start-state'};
 const readyDeadline=Date.now()+5000;while((!lastState||statePending)&&Date.now()<readyDeadline)await new Promise(resolve=>setTimeout(resolve,20));
 ensure(lastState);await action('state');ensure(byId('start').disabled&&!byId('configure').disabled);
 await button('nav-routing');ensure(!byId('view-routing').hidden&&byId('view-overview').hidden&&byId('nav-routing').getAttribute('aria-selected')==='true');ensure(byId('compact-state').textContent==='默认关闭 · 501'&&!byId('routing-details').open);byId('routing-details').querySelector('summary').click();ensure(byId('routing-details').open);byId('routing-details').querySelector('summary').click();ensure(!byId('routing-details').open);
 await button('nav-settings');ensure(!byId('view-settings').hidden&&byId('view-routing').hidden);
 await button('diagnostics-refresh');const diagnostic=JSON.parse(byId('diagnostics-report').textContent);ensure(diagnostic.scope==='current-core'&&!diagnostic.gateway.configured&&!diagnostic.verified_upstream&&!byId('diagnostics-report').hidden&&!byId('diagnostics-report').textContent.includes('mock.example'));await button('diagnostics-clear');ensure(byId('diagnostics-report').hidden&&byId('diagnostics-report').textContent==='');
 await button('nav-overview');ensure(!byId('view-overview').hidden);
 await button('nav-integrations');ensure(!byId('view-integrations').hidden&&!byId('codex-contract').open&&!byId('integration-boundaries').open);byId('codex-contract').querySelector('summary').click();ensure(byId('codex-contract').open);byId('codex-contract').querySelector('summary').click();byId('integration-boundaries').querySelector('summary').click();ensure(byId('integration-boundaries').open);byId('integration-boundaries').querySelector('summary').click();ensure(byId('integration-gateway').textContent==='尚未配置网关');await button('skill-copy');await button('mcp-copy');await button('codex-copy');await button('codex-catalog-copy');
 byId('codex-route-mode').value='native';window.confirm=()=>true;ensure(byId('codex-route-apply').disabled);await button('codex-route-preview');ensure(!byId('codex-route-apply').disabled&&byId('codex-route-result').textContent.includes('尚未写入'));await button('codex-route-apply');ensure(byId('codex-route-apply').disabled&&byId('codex-route-result').textContent.includes('已应用配置'));
 await button('nav-overview');ensure(byId('quota-refresh').disabled);
 byId('endpoint').value='https://mock.example';byId('key').value='synthetic-appcheck-only';byId('remember').checked=true;
 await button('configure');ensure(byId('key').value===''&&lastState.Configured);
 byId('endpoint').value='https://other.example';byId('key').value='synthetic-other';byId('remember').checked=false;
 await button('configure');await button('nav-settings');await button('load');ensure(byId('endpoint').value==='https://mock.example'&&!byId('view-overview').hidden&&byId('view-settings').hidden);
 await button('quota-refresh');ensure(byId('quota-available').textContent.includes('12,345')&&byId('quota-note').textContent.includes('非账户钱包')&&!byId('state').textContent.includes('private-do-not-render'));
 await button('models-refresh');ensure(byId('models-state').textContent==='列表权限已验证'&&byId('models-list').textContent==='mock'&&byId('models-note').textContent.includes('不证明模型推理可用'));byId('models-filter').value='absent';byId('models-filter').oninput();ensure(byId('models-list').textContent==='没有匹配的模型');byId('models-filter').value='';byId('models-filter').oninput();ensure(byId('models-list').textContent==='mock');
 await start('passthrough');ensure(lastState.Running&&byId('configure').disabled&&byId('load').disabled&&byId('start').disabled&&!byId('stop').disabled&&!byId('quit').disabled);
 step='passthrough-start-render';
 ensure(byId('service-state').textContent==='运行中'&&byId('status-badge').dataset.tone==='good'&&byId('local-url').textContent===lastState.LocalEndpoint+'/v1');
 await button('nav-settings');await button('diagnostics-refresh');const runningDiagnostic=JSON.parse(byId('diagnostics-report').textContent);ensure(runningDiagnostic.gateway.running&&runningDiagnostic.gateway.configured&&runningDiagnostic.gateway.listener_allocated&&!byId('diagnostics-report').textContent.includes('synthetic-appcheck-only')&&!byId('diagnostics-report').textContent.includes('mock.example'));await button('nav-overview');
 await button('nav-integrations');ensure(!byId('view-integrations').hidden&&!byId('image-mcp-copy').disabled&&byId('integration-gateway').textContent==='本地网关运行中');await button('image-mcp-copy');ensure(!byId('video-mcp-copy').disabled);await button('video-mcp-copy');await button('nav-overview');
 // Test-only synthetic consent dialog, not an alternate handler/fetch path.
 window.confirm=()=>true;await button('nav-images');ensure(!byId('view-images').hidden);await button('image-catalog');ensure(byId('image-model').value===''&&byId('image-generate').disabled);byId('image-model').value='momoapi-gpt-image-2-5-flare';byId('image-model').onchange();byId('image-prompt').value='media-probe';byId('image-options').value='{}';byId('image-consent').checked=true;byId('image-consent').oninput();await button('image-generate');ensure(byId('image-result-state').textContent==='任务待完成'&&!byId('image-consent').checked&&!byId('image-task').disabled);await button('image-task');ensure(byId('image-result-state').textContent==='已返回结果'&&byId('image-task').disabled&&byId('image-results').textContent.includes('https://images.example/probe.png')&&!byId('image-preview').getAttribute('src'));byId('image-prompt').value='gui-inline-probe';byId('image-consent').checked=true;byId('image-consent').oninput();await button('image-generate');ensure(byId('image-preview').hidden&&!byId('image-preview').getAttribute('src'));step='image-preview';byId('image-results').querySelector('button').click();ensure(!byId('image-preview').hidden&&byId('image-preview').src.startsWith('data:image/png;base64,'));const previewDeadline=Date.now()+2000;while(!byId('image-preview').complete&&Date.now()<previewDeadline)await new Promise(r=>setTimeout(r,20));ensure(byId('image-preview').naturalWidth===1);byId('image-operation').value='edit';byId('image-operation').onchange();ensure(!byId('image-reference-field').hidden&&!byId('image-consent').checked);step='image-reference-select';const selectedBytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='),c=>c.charCodeAt(0));const selectedFiles=new DataTransfer();selectedFiles.items.add(new File([selectedBytes],'synthetic-private-reference.png',{type:'image/png'}));byId('image-reference-files').files=selectedFiles.files;ensure(await byId('image-reference-files').onchange());ensure(localImageReferences.length===1&&byId('image-reference-list').querySelectorAll('button').length===2&&!byId('image-reference-preview').getAttribute('src')&&!byId('image-consent').checked);step='image-reference-preview';byId('image-reference-list').querySelector('button').click();const localPreviewDeadline=Date.now()+2000;while(!byId('image-reference-preview').complete&&Date.now()<localPreviewDeadline)await new Promise(r=>setTimeout(r,20));ensure(byId('image-reference-preview').naturalWidth===1);byId('image-prompt').value='edit-gui';byId('image-consent').checked=true;byId('image-consent').oninput();await button('image-generate');ensure(!byId('image-consent').checked&&!byId('image-task').disabled);await button('image-task');ensure(byId('image-results').textContent.includes('edited.png')&&byId('image-task').disabled);await button('nav-overview');
 byId('image-model').value='gemini-3.1-flash-image';byId('image-model').onchange();byId('image-operation').value='edit';byId('image-operation').onchange();byId('image-references').value='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';byId('image-prompt').value='gemini-edit-gui';byId('image-consent').checked=true;byId('image-consent').oninput();await button('image-generate');ensure(byId('image-result-state').textContent==='已返回结果'&&byId('image-task').disabled&&byId('image-results').querySelectorAll('button').length===2);
 step='image-save';renderImageResult({images:[{b64_json:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',mime_type:'image/png'}],terminal:true},'generate');await byId('image-results').querySelectorAll('button')[1].onclick();ensure(byId('image-result-note').textContent.includes('已保存'));
 await button('nav-videos');ensure(!byId('view-videos').hidden);await button('video-catalog');ensure(byId('video-model').value===''&&byId('video-generate').disabled);byId('video-model').value='seedance-2.5';byId('video-model').onchange();ensure(byId('video-duration').value===''&&byId('video-resolution').value===''&&byId('video-ratio').value==='');byId('video-duration').value='4';byId('video-resolution').value='480p';byId('video-ratio').value='adaptive';byId('video-prompt').value='video-gui-probe';byId('video-consent').checked=true;byId('video-consent').oninput();await button('video-generate');ensure(byId('video-result-state').textContent==='任务待完成'&&!byId('video-consent').checked&&!byId('video-task').disabled);await button('video-task');ensure(byId('video-result-state').textContent==='视频已完成'&&byId('video-task').disabled&&byId('video-results').textContent==='https://video.example/probe.mp4'&&!byId('video-results').querySelector('video,iframe,a,img'));await button('nav-overview');
 await request('check-proxy');await request('check-native-stop');
 const deadline=Date.now()+5000;while(lastState.Running&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,100));
 ensure(!lastState.Running&&!byId('start').disabled&&!byId('configure').disabled);
 ensure(byId('status-label').textContent==='已停止');
 ensure(byId('diagnostics-report').hidden&&byId('diagnostics-report').textContent==='');
 ensure(byId('image-results').textContent===''&&byId('image-preview').hidden&&!byId('image-preview').getAttribute('src')&&byId('image-catalog').disabled&&localImageReferences.length===0&&byId('image-reference-list').textContent===''&&byId('image-reference-preview').hidden&&!byId('image-reference-preview').getAttribute('src'));
 ensure(byId('video-results').textContent===''&&byId('video-prompt').value===''&&byId('video-catalog').disabled&&byId('video-model').value===''&&!byId('video-consent').checked);
 byId('routing-mode').checked=true;byId('key').value='synthetic-appcheck-only';await button('configure');ensure(lastState.Mode==='momo-routing');
 await start('routing');ensure(lastState.Running&&byId('routing-mode').disabled);step='routing-start-render';ensure(byId('routing-state').textContent.includes('已启用')&&byId('compact-state').textContent==='部分支持 · 手动回放');await request('check-routing');await request('check-stall');await button('stop');await request('check-done');
}
check().catch(()=>{const allowed=['initial','nav-videos','video-catalog','video-generate','video-task','nav-routing','nav-settings','diagnostics-refresh','diagnostics-clear','nav-overview','nav-integrations','nav-images','image-catalog','image-generate','image-task','image-preview','image-reference-select','image-reference-preview','image-save','skill-copy','mcp-copy','image-mcp-copy','video-mcp-copy','codex-copy','codex-catalog-copy','configure','load','quota-refresh','models-refresh','start','passthrough-start-enabled','passthrough-start-action','passthrough-start-state','passthrough-start-render','routing-start-enabled','routing-start-action','routing-start-state','routing-start-render','check-proxy','check-native-stop','check-routing','check-stall','stop','check-done'];const step=window.momoProbeStep?.();fetch('/check-page-failure?step='+(allowed.includes(step)?step:'unknown'),{method:'POST',headers:{'X-MOMO-Bridge':bridgeNonce}}).catch(()=>{});});
`
