import assert from 'node:assert/strict';
import {createMomoSwitch} from '../../src/server.mjs';
const nl='\n';
const chat=(count,kind)=>'data: '+JSON.stringify({choices:[{index:0,delta:{tool_calls:Array.from({length:count},(_,index)=>({index,id:'single_'+index,type:'function',function:{name:'pad__read',arguments:JSON.stringify(kind==='custom'?{input:'raw 中文🙂'}:{x:1})}}))},finish_reason:'tool_calls'}]})+nl+nl+'data: [DONE]'+nl+nl;
const cf=(type,f={})=>'event: '+type+nl+'data: '+JSON.stringify({type,...f})+nl+nl;
const claude=(count,kind)=>cf('message_start',{message:{id:'msg_single',type:'message',role:'assistant',model:'claude-sonnet-4-6',content:[],usage:{input_tokens:3,output_tokens:1}}})+Array.from({length:count},(_,index)=>cf('content_block_start',{index,content_block:{type:'tool_use',id:'single_'+index,name:'pad__read',input:{}}})+cf('content_block_delta',{index,delta:{type:'input_json_delta',partial_json:JSON.stringify(kind==='custom'?{input:'raw 中文🙂'}:{x:1})}})+cf('content_block_stop',{index})).join('')+cf('message_delta',{delta:{stop_reason:'tool_use',stop_sequence:null},usage:{output_tokens:5}})+cf('message_stop');
const gemini=(count,kind)=>'data: '+JSON.stringify({candidates:[{index:0,content:{role:'model',parts:Array.from({length:count},(_,i)=>({functionCall:{id:'single_'+i,name:'pad__read',args:kind==='custom'?{input:'raw 中文🙂'}:{x:1}}}))},finishReason:'STOP'}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:5,totalTokenCount:8}})+nl+nl;
const specs=[{model:'gpt-5.5',path:'/v1/chat/completions',fixture:chat},{model:'claude-sonnet-4-6',path:'/v1/messages',fixture:claude},{model:'gemini-2.5-flash',path:'/v1beta/models/gemini-2.5-flash:streamGenerateContent',fixture:gemini}];
export async function parallelToolsBlackbox(launch,invoke){
 let cases=0;
 for(const spec of specs)for(const streaming of [true,false])for(const kind of ['function','custom'])for(const count of [1,2]){
  const {child,handoff}=await launch({path:spec.path,stream:spec.fixture(count,kind)});let server;
  try{
   const env={MOMO_PROXY_HOME:'unused-parallel-profile',MOMO_PROXY_CONSOLE_MIRROR:'0'};
   server=createMomoSwitch({endpoint:'https://mock.example',apiKey:'synthetic-unified-only',localToken:'synthetic-node-only',host:'127.0.0.1',port:0,diagnosticsEnabled:false,requestAdmission:{maxConcurrent:4,maxQueued:0,maxBodyBudgetMb:4,bodyReadTimeoutMs:15000},contextPolicy:{outboundBodyHardLimitBytes:1048576,outboundBodySoftLimitBytes:1047552},outputPolicy:{maxStreamMb:16,maxRetainedMb:1}},{env,loggingRuntime:{env,enqueueRequest:()=>true,enqueueDiagnostic:()=>true,snapshot:()=>({})},assetStore:{},attachmentAssetStore:{},fetchImpl:(url,init)=>{const u=new URL(url);assert.equal(u.hostname,'mock.example');return fetch(handoff.mock_url+u.pathname+u.search,init)}});
   await new Promise(r=>server.listen(0,'127.0.0.1',r));const nodeURL='http://127.0.0.1:'+server.address().port,goURL=handoff.base_url.slice(0,-3);
   const p={model:spec.model,stream:streaming,parallel_tool_calls:false,input:[{role:'user',content:'single-shared-turn'}],tools:[{type:'namespace',name:'pad',tools:[{type:kind,name:'read'}]}]};
   const n=await invoke(nodeURL,'synthetic-node-only',p),g=await invoke(goURL,handoff.api_key,p);assert.equal(n.status,200);assert.ok(n.completed);assert.equal(n.output.length,count);
   if(count===1){assert.equal(g.status,200);assert.ok(g.completed);assert.equal(g.output.length,1);assert.equal(g.output[0].call_id,'single_0');assert.equal(g.output[0].namespace,'pad');assert.equal(g.output[0].name,'read');assert.equal(n.output[0].namespace,undefined);const normalized=structuredClone(n.output);normalized[0].namespace='pad';if(kind==='custom'){assert.equal(g.output[0].input,'raw 中文🙂');assert.equal(n.output[0].input,'await tools.exec_command({ cmd: '+JSON.stringify('raw 中文🙂')+' });');normalized[0].input='raw 中文🙂'}assert.deepEqual(g.output,normalized)}else{assert.equal(g.completed,undefined);assert.equal(g.incomplete,undefined);if(!streaming)assert.equal(g.status,502);else assert.ok(g.truncated,'stream error must abort, not complete')}
   const captures=await(await fetch(handoff.mock_url+'/capture')).json();assert.equal(captures.length,2,'exactly one send per implementation; no retry');const [node,go]=captures;
   if(spec.model==='gpt-5.5'){assert.equal(go.parallel_tool_calls,false);assert.equal(node.parallel_tool_calls,undefined)}else if(spec.model.startsWith('claude')){assert.equal(go.tool_choice.disable_parallel_tool_use,true);assert.equal(node.tool_choice?.disable_parallel_tool_use,undefined)}else{assert.ok(!JSON.stringify(go).includes('parallel'));assert.ok(!JSON.stringify(node).includes('parallel'))}
   console.log('PASS shared single-call constraint '+spec.model+' '+kind+' '+(streaming?'SSE':'JSON')+' '+count+' calls; identical mock/resources/input, explicit Go mapping and local rejection vs Node omitted constraint/acceptance independently asserted; not provider constrained-generation guarantee');cases++;
  }finally{if(server)await new Promise(r=>{server.close(r);server.closeAllConnections()});child.kill();await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,3000))]);}
 }return cases;
}
